apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: develop
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  #externalIPs:
    #- 34.243.145.83
